from typing import overload, Iterator, List, Union

import numpy as np

from .colors import ColorRGB, ColorRGBRef, ColorHSV
from .LedStrip import LedStrip

Color = Union[ColorRGB, ColorRGBRef, ColorHSV]

class LedStripSet:
    @overload
    def __init__(self, strips: List[LedStrip]) -> None: ...
    @overload
    def __init__(self, stripSets: List["LedStripSet"]) -> None: ...
    @property
    def red(self) -> np.ndarray: ...
    @property
    def green(self) -> np.ndarray: ...
    @property
    def blue(self) -> np.ndarray: ...
    @overload
    def __getitem__(self, index: int) -> ColorRGB: ...
    @overload
    def __getitem__(self, index: slice) -> "LedStripSet": ...
    @overload
    def __setitem__(self, index: int, color: Color) -> None: ...
    @overload
    def __setitem__(self, index: slice, color: Union[LedStrip, "LedStripSet"]) -> None: ...
    @overload
    def __setitem__(self, index: int, red: int, green: int, blue: int) -> None: ...
    @overload
    def __setitem__(self, index: np.ndarray, color: Union[LedStrip, "LedStripSet"]) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Color]: ...
    def size(self) -> int: ...
    def isOn(self) -> bool: ...
    @overload
    def fill(self, red: int, green: int, blue: int) -> None: ...
    @overload
    def fill(self, color: Color) -> None: ...
    def clear(self) -> None: ...
    def left(self, num: int, fill: Color) -> None: ...
    def right(self, num: int, fill: Color) -> None: ...
    def brightness(self) -> np.ndarray: ...
    @overload
    def getHSV(self, index: int) -> ColorHSV: ...
    @overload
    def getHSV(self) -> np.ndarray: ...
    @overload
    def setHSV(self, hsv: np.ndarray) -> None: ...
    @overload
    def setHSV(self, hue: np.ndarray, saturation: np.ndarray, value: np.ndarray) -> None: ...
